#!/bin/sh

#This script runs a set of phonons for bcc na. Input is the volume to run at

cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
MASTER=`pwd`
dir="$1"
SCRATCH_DIR="/scratch/s1333534/na_bcc_phon/$dir"

mkdir -p "$SCRATCH_DIR"
cd "$SCRATCH_DIR"

cat > na.bcc.scf.in << EOF
&control
	calculation = 'scf',
	prefix = 'na.bcc',
	tstress = .true.,
/
&system
	ibrav = 3,
	celldm(1) = $dir,
	nat = 1,
	ntyp = 1,
	ecutwfc = 40,
	ecutrho = 320,
	occupations = 'smearing',
	smearing = 'm-v',
	degauss = 0.02,
/
&electrons
	mixing_beta = 0.7,
	conv_thr = 1.0d-8,
/
ATOMIC_SPECIES
 Na 22.99 Na_pbe_v1.uspp.F.UPF
ATOMIC_POSITIONS crystal
 Na 0 0 0
K_POINTS automatic
 14 14 14 1 1 1
EOF

mpirun -np 4 pw.x < na.bcc.scf.in > na.bcc.scf.out

cat > na.bcc.ph.in << EOF
BCC Na Phonon Calculation 
&inputph
	prefix = 'na.bcc',
	ldisp = .true.,
	nq1 = 8,
	nq2 = 8,
	nq3 = 8,
	fildyn = 'na.bcc.dyn',
/
EOF

mpirun -np 4 ph.x < na.bcc.ph.in > na.bcc.ph.out

cp *.dyn* *.in *.out "$MASTER/$dir"
