#!/bin/bash --login
#PBS -N li-fcc-40
#PBS -V
#PBS -l select=16
#PBS -l walltime=01:00:00

# Make sure you change this to your budget code
#PBS -A e89-ed_p

# Make sure any symbolic links are resolved to absolute path
export PBS_O_WORKDIR=$(readlink -f $PBS_O_WORKDIR)

# Change to the directory that the job was submitted from
cd $PBS_O_WORKDIR

# Clean temporary files
#rm -rf tmp/*

# Load the CASTEP module
#module add espresso
which pw.x
which ph.x

# This line sets the temporary directory - without it CASTEP will fail
export GFORTRAN_TMPDIR=$PBS_O_WORKDIR
export OMP_NUM_THREADS=1

aprun -n 384 -N 24 pw.x -npool 384 < fcc-li.scf >> fcc-li.scf.out
aprun -n 384 -N 24 ph.x -npool 384 < fcc-li.ph  >> fcc-li.ph.out


