#!/bin/sh

cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
MASTER=`pwd`

for dir in `ls -l | grep '^d' | awk '{print $9 }'`; do
	cd "$MASTER/$dir"
	cat > na.fcc.scf.in << EOF
&control
	calculation = 'scf',
	prefix = 'na.fcc',
	tstress = .true.,
/
&system
	ibrav = 2,
	celldm(1) = $dir,
	nat = 1,
	ntyp = 1,
	ecutwfc = 40,
	ecutrho = 320,
	occupations = 'smearing',
	smearing = 'm-v',
	degauss = 0.02,
/
&electrons
	mixing_beta = 0.7,
	conv_thr = 1.0d-8,
/
ATOMIC_SPECIES
 Na 22.99 Na_pbe_v1.uspp.F.UPF
ATOMIC_POSITIONS crystal
 Na 0 0 0
K_POINTS automatic
 14 14 14 1 1 1
EOF
	cd "$MASTER"
done
