#!/bin/sh

cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
MASTER=`pwd`

for dir in `ls -l | grep '^d' | awk '{print $9 }'`; do
	echo "$dir"
	cd "$MASTER/$dir"
	cat > na.bcc.fqha.in << EOF
na.bcc.303030.simple.dos
na.bcc.fqha.calc
0
10
20
30
40
50
60
70
80
90
100
110
120
130
140
150
160
170
180
EOF
	fqha.x < na.bcc.fqha.in > na.bcc.fqha.out
	cd "$MASTER"
done
