#!/bin/bash --login
#$ -N na-hcp-relax
#$ -V
#$ -pe mpi 64
#$ -q sopa.1.day
#PBS -l l_hrt=23:58:00

hostname

echo $SGE_O_WORKDIR

export SGE_O_WORKDIR=$(readlink -f $SGE_O_WORKDIR)

MASTER_DIR="/home/s1333534/hcp_sn_relax/"
cd "$MASTER_DIR"

pwd

export PW=/home/s1333534/quantum_espresso/qe-6.1/bin/pw.x
export PH=/home/s1333534/quantum_espresso/qe-6.1/bin/ph.x
export ESPRESSO_PSEUDO=/home/s1333534/quantum_espresso/qe-6.1/pseudo

export OMP_NUM_THREADS=1

cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname

SCRATCH_DIR="/scratch/s1333534/na_hcp_relax/"
NUMCORES=64

rm -rf $SCRATCH_DIR
mkdir -p $SCRATCH_DIR


cd "$SCRATCH_DIR"
cat > na.hcp.relax.in << EOF
&control
	calculation='vc-relax',
	prefix='na_hcp',
/
&system
        ibrav = 4,
        celldm(1) = 6.9938505,
	celldm(3) = 1.63046036,
        nat = 2,
        ntyp = 1,
        ecutwfc = 40,
        ecutrho = 320,
        occupations = 'smearing',
        smearing = 'm-v',
        degauss = 0.02,
/
&electrons
        mixing_beta = 0.7,
        conv_thr = 1.0d-7,
/
&IONS
/
&CELL
press_conv_thr=0.01D0
/
ATOMIC_SPECIES
 Na 22.99 Na_pbe_v1.uspp.F.UPF
ATOMIC_POSITIONS (crystal)
Na       0.0 0.0 0.0
Na       0.666666 0.333333 0.5
K_POINTS automatic
 20 20 20 1 1 1
EOF
	mpirun -np $NUMCORES $PW < na.hcp.relax.in | tee na.hcp.relax.out
	cp *.in *.out "$MASTER_DIR"
