#!/bin/sh
#Uses same input as run_phonons_ssh but just closes all tmux sessions on those computers
COMPS="$1"
COMP=0
echo "$COMPS"
while read -r line; do
        if [ "${line:0:1}" = "!" ]; then
                COMP=${line:2}
                echo "$COMP"
        else
                ssh s1333534@cplab$COMP /bin/bash <<'EOT'
                export TERM=xterm
                tmux kill-server
EOT
        fi

done <<< "$COMPS"
