#!/bin/sh
#This script allows splitting up of a phonon job over multiple computers on the ssh network, so each one does a certain number of the phonons.
COMPS="$1"
COMP=0
while read -r line; do
	if [ "${line:0:1}" = "!" ]; then
		COMP=${line:2}
		echo "$COMP"
	else
		echo "$line"
	fi

done <<< $COMPS
