#!/bin/bash --login
#$ -N na-fcc-ph-s1333534
#$ -V
#$ -pe mpi 64
#$ -q sopa.1.day
#PBS -l l_hrt=23:58:00

hostname
#module load mpi/openmpi-x86_64

echo $SGE_O_WORKDIR

export SGE_O_WORKDIR=$(readlink -f $SGE_O_WORKDIR)

MASTER_DIR=/home/s1333534/git/Sodium-DFT-Project/Na_Phonons/FCC_phonons_0gpa_666/
cd $MASTER_DIR

pwd

export PW=/home/s1333534/quantum_espresso/qe-6.1/bin/pw.x
export PH=/home/s1333534/quantum_espresso/qe-6.1/bin/ph.x
export ESPRESSO_PSEUDO=/home/s1333534/quantum_espresso/qe-6.1/pseudo

export OMP_NUM_THREADS=1

cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
ECUTWFC=50
ECUTRHO=`expr 8 \* $ECUTWFC`
NUMCORES=64

#### CAREFUL WITH THIS
rm -rf /scratch/s1333534/na.fcc.phonon/
mkdir -p /scratch/s1333534/na.fcc.phonon/
cd /scratch/s1333534/na.fcc.phonon/
#The self-consistent calculation script
cat > na.fcc.scf.in << EOF
&control
        calculation = 'scf',
        prefix = 'na.fcc',
        tstress = .true.,
/
&system
        ibrav = 2,
        celldm(1) = 9.882457429601098,
        nat = 1,
        ntyp = 1,
        ecutwfc = 40,
        ecutrho = 320,
        occupations = 'smearing',
        smearing = 'm-v',
        degauss = 0.02,
/
&electrons
        mixing_beta = 0.7,
        conv_thr = 1.0d-10,
/
ATOMIC_SPECIES
 Na 22.99 Na_pbe_v1.uspp.F.UPF
ATOMIC_POSITIONS crystal
 Na 0 0 0
K_POINTS automatic
 20 20 20 1 1 1
EOF
        mpirun -np $NUMCORES $PW -nk 4 < na.fcc.scf.in | tee na.fcc.scf.out
#        cp *.dyn* $MASTER_DIR
        cat > na.fcc.ph.in << EOF
Na FCC Phonon Calculation
&inputph
        prefix = 'na.fcc',
	tr2_ph = 1e-16,
        ldisp = .true.,
        nq1 = 6,
        nq2 = 6,
        nq3 = 6,
        fildyn = 'na.fcc.dyn',
/
EOF
        echo "Calculating phonons"
        mpirun -np $NUMCORES $PH -nk 4 < na.fcc.ph.in | tee na.fcc.ph.out
        cp *.dyn* $MASTER_DIR
        cd $MASTER_DIR
