#!/bin/sh
MASTER=`pwd`
mkdir extracted
echo "$MASTER"
for f in `ls vol/`; do
	cd "vol/$f"
	this_vol=`grep -r "3, celldm(1)=" | awk '{print $5}'`
	echo $this_vol
	cd "$MASTER"
	cp "vol/$f/fqha.out40" "extracted/bcc.fqha.$this_vol"
	cp "vol/$f/bcc-li.scf.out" "extracted/bcc-li.scf.out.$this_vol"
done
